@since(version = 0.1.0)
interface service {
  type service-id = u32;

  enum restart-state {
    SUCESS,
    FAILED,
  }

  resource service {
    constructor(id: service-id);

    restart: func() -> restart-state;
  }

  current: func() -> service;
}
