package imago:nanokvm@0.1.0;

@since(version = 0.1.0)
interface capture {
  use wasi:io/streams@0.2.7.{input-stream};
  use auth.{auth};

  @since(version = 0.1.0)
  capture: func(auth: borrow<auth>) -> result<tuple<u64, input-stream>, string>;
}

@since(version = 0.1.0)
interface auth {
  resource auth {
    constructor(hostname: string, username: string, password: string);
    get-auth-token: func() -> string;
    get-hostname: func() -> string;
  }
}

@since(version = 0.1.0)
world imports {
  @since(version = 0.1.0)
  import capture;
  @since(version = 0.1.0)
  import auth;
}
